apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    #feature.node.kubernetes.io/custom-silicom.fpga.lc: "true"
    machineconfiguration.openshift.io/role: master
  name: 88-test-machine-labels
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,Q1JJT19DT05GSUdfT1BUSU9OUz0tLWluc2VjdXJlLXJlZ2lzdHJ5PWRvY2tlci5zaWxpY29tLmRrOjUwMDA=
        filesystem: root
        overwrite: true
        mode: 0420
        path: /root/crio